### ISSUE TITLE
Add Offline Label

### ISSUE THREAD

**Issue by TwisterMc** [Moustachauve/WLED-Native-iOS#10]
In the WLED app, they put "Offline" after any device that the app knows about, but isn't currently online. 
![IMG_13224DB818F9-1](https://github.com/Moustachauve/WLED-Native-iOS/assets/46997/18567e55-d6cb-4255-99fe-f508dd090cdb)

In WLED Native, there's no indication of what's online or offline.
![IMG_DB78B33D39F5-1](https://github.com/Moustachauve/WLED-Native-iOS/assets/46997/51673653-9ac2-478e-bb01-4485f74650d4)

I do not always have my devices connected to the internet, nor do I remember the name of each device, so when I power one up, it's nice to know which devices are online vs which ones are offline.

**Comment by Moustachauve** [comment]
That's strange, it should show both offline and have a wifi icon with a bar through it to show that it is not online. What version of the app are you using?

**Comment by TwisterMc** [comment]
2.0 which is what's in the AppStore

**Comment by Moustachauve** [comment]
The newest version should fix this.
