### ISSUE TITLE
Odd Behavior Using WLED-Native-iOS

### ISSUE THREAD

**Issue by Grizz952** [Moustachauve/WLED-Native-iOS#11]
Hi Moustachauve,
I was referred to you by blazoncek (on WLED discourse).  I'm observing odd behavior when using WLED-Native-iOS.

I have three independent LED strings established, each with a unique IP address. All strings are logged onto my home wifi, and are visible in WLED-Native-iOS (two phones, wife's and mine). When my wife turns (the two sets of) Christmas lights on or off, it also impacts my sound reactive string (in the basement). The basement string seems to revert to whatever settings my wife has selected. I’m able to (daily) reset my basement string to my desired settings without further incident. But, next time she turns Christmas off, they will change again. Has anyone else encountered similar behavior? Any thoughts on resolving?

Thanks,  Grizz952

**Comment by Moustachauve** [comment]
That's very weird, that's not something that should be possible currently. I'm currently writing a new version of the app for iOS almost from scratch, so hopefully this will  help with your issue. Are you sure none of your WLED devices have the sync option enabled?
