### ISSUE TITLE
WLED Native App shutting down WLED instances

### ISSUE THREAD

**Issue by Bennobear** [Moustachauve/WLED-Native-iOS#16]
Hey Christophe, 

there seems to be a problem with the newest WLED Native Version. 
I just got into this LED and WLED stuff but i've ran into a peculiar problem when using the WLED Native app.
Opening the App shuts down any WLED instance it finds, not everytime but opening the app a few times and they will shut down. 
 
I posted on Reddit to see if it's a common issue, and maybe somethings wrong with my settings, but from the few replies it seems to be a problem caused by the App on iOS specifically: https://www.reddit.com/r/WLED/comments/1abh212/wled_stops_working_when_opening_the_native_wled/

**Comment by Moustachauve** [comment]
Thanks for bringing this issue to my attention. I'll start investigating why this happens.

**Comment by Bennobear** [comment]
I installed the WLED Debug build and ran a Serial Monitor.
I hoped they would throw some exceptions.
That's the log when i open the app and the instance shuts down.

---DEBUG INFO---
Runtime: 900492
Unix time: 1706350824,492
Free heap: 202600
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.178.121
Loops/sec: 2547
Loop time[ms]: 11/4
UM time[ms]: 0/1
Strip time[ms]: 0/1
Segments: 1 -> 68B
Modes: 4*187=748B
Data: 4*187=748B
Map: 2*0=0B
Buffer: 3*30=90B
JSON buffer locked. (17)
JSON buffer size: 2165 for request: 3
JSON content length: 1197
ERROR: Locking JSON buffer failed! (17)
ERROR: Locking JSON buffer failed! (17)

Weird part is i can't find which Module number 17 is suppose to be.

**Comment by Moustachauve** [comment]
I'm deploying a new version that should be available soon that should hopefully address this issue!

**Comment by Moustachauve** [comment]
@Bennobear Please let me know if you have time if this issue is improved with the latest version of the app (6)

**Comment by Bennobear** [comment]
Hey Christophe,

i had to manually update the App but since then it didn't crash, even with vigorous testing.


Thanks for the quick fix! 
I already posted on the Reddit Threat that people need to look out for the update because the automatic updates from the App Store can take a few weeks.
Maybe you can make a post separate post about the update. 

The Google Play Console has an option to prompt users to update to the latest versions but I don't think the Apple Store Connect has something like that unfortunately. 

Best regards 
Ben
