### ISSUE TITLE
Hidden devices stop being hidden after app restart.

### ISSUE THREAD

**Issue by TheParzivall** [Moustachauve/WLED-Native-iOS#4]
I'm hiding ip addresses, they appear again after the application is closed, I would appreciate it if you could solve it.

Your work is very nice, congratulations. Good work

**Comment by Moustachauve** [comment]
Hello,

What do you mean by hiding ip address? That's not a feature available currently

**Comment by TheParzivall** [comment]
I'm hiding the hide option from here, it hides, but when I close the application and open it again, the privacy feature is disabled and appears on the home page.
![image](https://user-images.githubusercontent.com/108283801/231798855-ee913126-5897-4311-839f-e6a16cfe17bf.jpeg)

**Comment by Moustachauve** [comment]
Ah, thanks for the bug report, I will look into it!

**Comment by TheParzivall** [comment]
When will it update the bug?
Application Perfect would be complete if you solve this problem

**Comment by Moustachauve** [comment]
This should be fixed now since version 2. More improvements are coming very soon for device synchronization in version 3.
