### ISSUE TITLE
possible type in readme

### ISSUE THREAD

**Issue by lost-hope** [Moustachauve/WLED-Native-iOS#7]
Hey, 
just noticed that you write in the readme that it is not a official Google product etc. 
Possibly an copy paste error from the Android app repo.
![image](https://github.com/Moustachauve/WLED-Native-iOS/assets/6001498/e2283001-02f4-40bb-abad-95c700639674)

**Comment by Moustachauve** [comment]
Hey @lost-hope,

No, this is not a typo. This disclaimer is required by my employer, as far as I understand, on all my projects I contribute to during my employment.
