### ISSUE TITLE
Add link to WLED documentation to README

### ISSUE THREAD

**Issue by hmahoney** [Moustachauve/WLED-Native-iOS#8]
It would be nice to add the link to the WLED documentation to the README. New users would have a much easier time with a reference, especially if they are new to LED lighting.

Here is the link:  https://kno.wled.ge

**Comment by Moustachauve** [comment]
Thanks for the feedback! I agree. I think it might even be great to add some links to WLED and the WLED documentation directly in the application too.

**Comment by hmahoney** [comment]
That's an excellent idea! Then the user doesn't have to figure out to go to the developer website from the App Store to find the README.
